# <center> **Numpy Array Operations**
#### <center> By: Johann Sebastian E. Catalla, BSCS-III
#### <center> An output for the course Data Science Fundamentals
***

In [57]:
import numpy as np
import pandas as pd
arr_from_list = np.array([10, 20, 30, 15, 20, 55, 60, 0, -10, 70, -12])
arr_from_list

array([ 10,  20,  30,  15,  20,  55,  60,   0, -10,  70, -12])

### Slicing Array

In [37]:
sliced_array = arr_from_list[1:4]
sliced_array

array([20, 30, 15])

### Generating array using different numpy functions

In [27]:
# Array of zeroes
zeros_array = np.zeros((3, 3))

# Array of homogeneous values
ones_array = np.ones((2, 4))

# Creating matrix
identity_array = np.eye(4)

# Creating array from range
range_array = np.arange(10, 20, 2)

# Evenly-spaced arrray
linspace_array = np.linspace(0, 100, 100)

# Random Array
random_array = np.random.rand(3, 900, 50)


In [4]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
identity_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
range_array

array([10, 12, 14, 16, 18])

In [19]:
linspace_array

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [33]:
random_array

array([[[0.1751334 , 0.99638179, 0.44322844, ..., 0.12625583,
         0.66388188, 0.73232631],
        [0.78891862, 0.52904501, 0.46089494, ..., 0.52196127,
         0.1425485 , 0.76237218],
        [0.8481597 , 0.27225465, 0.58679331, ..., 0.96370911,
         0.80435258, 0.94783065],
        ...,
        [0.05936496, 0.86476949, 0.32459472, ..., 0.41639091,
         0.27262116, 0.74632343],
        [0.9008081 , 0.17806964, 0.86449596, ..., 0.61097735,
         0.85360497, 0.0425169 ],
        [0.89118862, 0.43373282, 0.3271033 , ..., 0.62331085,
         0.75904239, 0.61954017]],

       [[0.91542873, 0.32338254, 0.16006715, ..., 0.52381475,
         0.84812675, 0.51751563],
        [0.82862421, 0.31331899, 0.7686042 , ..., 0.46980552,
         0.38578561, 0.51032539],
        [0.47826726, 0.3022152 , 0.96618631, ..., 0.64196106,
         0.69173366, 0.40233259],
        ...,
        [0.4550396 , 0.98675219, 0.43632351, ..., 0.20130782,
         0.4194328 , 0.70713744],
        [0.6

### Numpy Array Operations

In [40]:
# Reshaping array
reshaped_array = range_array.reshape((5, 1))
reshaped_array


array([[10],
       [12],
       [14],
       [16],
       [18]])

In [43]:
# Indexing and Slicing
sliced_array = arr_from_list[1:4]
sliced_array


array([20, 30, 15])

In [45]:
# Concatenation
concatenated_array = np.concatenate((arr_from_list, range_array))
concatenated_array

array([ 10,  20,  30,  15,  20,  55,  60,   0, -10,  70, -12,  10,  12,
        14,  16,  18])

In [49]:
# Addition Operation
sum_array = arr_from_list[:5] + range_array[:5]
sum_array

array([20, 32, 44, 31, 38])

In [51]:
# Multiplication Operation
product_array = arr_from_list * 2
product_array

array([ 20,  40,  60,  30,  40, 110, 120,   0, -20, 140, -24])

In [56]:
# Element-wise Multiplication
elementwise_multiplication = arr_from_list * np.tile(np.array([1, 2, 3, 4, 5]), len(arr_from_list)//5 + 1)[:len(arr_from_list)]
elementwise_multiplication


array([ 10,  40,  90,  60, 100,  55, 120,   0, -40, 350, -12])

### Reading a dataset and Converting it into a Numpy Array

In [67]:
dataset = pd.read_csv('vgsales.csv')
dataset = dataset.head(200)
dataset

Rank                                 Name Platform    Year         Genre  \
0       1                           Wii Sports      Wii  2006.0        Sports   
1       2                    Super Mario Bros.      NES  1985.0      Platform   
2       3                       Mario Kart Wii      Wii  2008.0        Racing   
3       4                    Wii Sports Resort      Wii  2009.0        Sports   
4       5             Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing   
..    ...                                  ...      ...     ...           ...   
195   196                       Guitar Hero II      PS2  2006.0          Misc   
196   197                      Resident Evil 5      PS3  2009.0        Action   
197   198                   Grand Theft Auto V     XOne  2014.0        Action   
198   199  Grand Theft Auto: Vice City Stories      PSP  2006.0        Action   
199   200                       FIFA Soccer 11      PS3  2010.0        Sports   

                Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
0                Nintendo     41.49     29.02      3.77         8.46   
1                Nintendo     29.08      3.58      6.81         0.77   
2                Nintendo     15.85     12.88      3.79         3.31   
3                Nintendo     15.75     11.01      3.28         2.96   
4                Nintendo     11.27      8.89     10.22         1.00   
..                    ...       ...       ...       ...          ...   
195             RedOctane      3.81      0.63      0.00         0.68   
196                Capcom      1.96      1.43      1.08         0.65   
197  Take-Two Interactive      2.66      2.01      0.00         0.41   
198  Take-Two Interactive      1.70      2.02      0.16         1.21   
199       Electronic Arts      0.60      3.29      0.06         1.13   

     Global_Sales  
0           82.74  
1           40.24  
2           35.82  
3           33.00  
4           31.37  
..            ...  
195          5.12  
196          5.11  
197          5.08  
198          5.08  
199          5.08  

[200 rows x 11 columns]

In [74]:
# sales from north america
na_sales = dataset['NA_Sales'].to_numpy()
na_sales

array([41.49, 29.08, 15.85, 15.75, 11.27, 23.2 , 11.38, 14.03, 14.59,
       26.93,  9.07,  9.81,  9.  ,  8.94,  9.09, 14.97,  7.01,  9.43,
       12.78,  4.75,  6.42, 10.83,  9.54,  9.63,  8.41,  6.06,  5.57,
        3.44,  6.85,  9.03,  5.89,  9.67,  5.17,  5.77,  4.99,  8.25,
        8.52,  5.54,  6.99,  6.75,  5.98,  2.55,  4.74,  7.97,  3.8 ,
        4.4 ,  6.91,  3.01,  6.16,  4.23,  6.16,  6.76,  4.02,  4.89,
        2.96,  4.99,  4.76,  5.99,  4.34,  5.08,  6.05,  6.72,  7.03,
        5.55,  3.66,  6.63,  3.01,  4.09,  5.84,  3.88,  5.91,  4.36,
        5.58,  2.01,  4.46,  5.03,  3.54,  1.11,  1.79,  6.82,  3.81,
        2.91,  1.06,  0.98,  5.8 ,  2.58,  2.91,  2.28,  2.82,  7.28,
        2.9 ,  3.66,  2.93,  2.8 ,  4.1 ,  3.78,  5.39,  3.24,  4.79,
        4.46,  3.83,  4.52,  3.51,  2.85,  3.27,  3.27,  3.68,  4.41,
        3.13,  2.47,  4.12,  4.14,  0.78,  2.71,  2.93,  2.77,  3.23,
        3.5 ,  4.15,  3.27,  3.1 ,  0.84,  1.67,  2.79,  0.79,  3.25,
        2.55,  3.74,

In [75]:
# Adding sales from all regions
total_game_sales = dataset['NA_Sales'] + dataset['EU_Sales'] + dataset['JP_Sales'] + dataset['Other_Sales']
total_game_sales.to_numpy()
total_game_sales

0      82.74
1      40.24
2      35.83
3      33.00
4      31.38
       ...  
195     5.12
196     5.12
197     5.08
198     5.09
199     5.08
Length: 200, dtype: float64

### Applying statistical functions

In [77]:
# Mean of total sales
mean_value = np.mean(total_game_sales, axis=0)
mean_value


10.291100000000002

In [79]:
# Median of total sales
median_value = np.median(total_game_sales, axis=0)
median_value

7.33

In [81]:
# Standard Deviation of total sales
std_dev = np.std(total_game_sales, axis=0)
std_dev


8.237470958370658

In [83]:
# Variance of total sales
variance = np.var(total_game_sales, axis=0)
variance

67.85592779000001

In [85]:
# Maximum value of total sales
max_value = np.max(total_game_sales, axis=0)
max_value

82.74000000000001

In [87]:
#Minimum value of total sales
min_value = np.min(total_game_sales, axis=0)
min_value

5.08

In [89]:
# Sum of total sales
sum_values = np.sum(total_game_sales, axis=0)
sum_values


2058.2200000000003

In [91]:
# Cumulative sum of total sales
cumsum_values = np.cumsum(total_game_sales, axis=0)
cumsum_values

0        82.74
1       122.98
2       158.81
3       191.81
4       223.19
        ...   
195    2037.85
196    2042.97
197    2048.05
198    2053.14
199    2058.22
Length: 200, dtype: float64