# <center> **Numpy Array Operations**
#### <center> By: Johann Sebastian E. Catalla, BSCS-III
#### <center> An output for the course Data Science Fundamentals
***

In [92]:
import numpy as np
import pandas as pd
arr_from_list = np.array([10, 20, 30, 15, 20, 55, 60, 0, -10, 70, -12])
arr_from_list

array([ 10,  20,  30,  15,  20,  55,  60,   0, -10,  70, -12])

### Slicing Array

In [93]:
sliced_array = arr_from_list[1:4]
sliced_array

array([20, 30, 15])

### Generating array using different numpy functions

In [94]:
# Array of zeroes
zeros_array = np.zeros((3, 3))

# Array of homogeneous values
ones_array = np.ones((2, 4))

# Creating matrix
identity_array = np.eye(4)

# Creating array from range
range_array = np.arange(10, 20, 2)

# Evenly-spaced arrray
linspace_array = np.linspace(0, 100, 100)

# Random Array
random_array = np.random.rand(3, 900, 50)


In [95]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [96]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [97]:
identity_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
range_array

array([10, 12, 14, 16, 18])

In [99]:
linspace_array

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [100]:
random_array

array([[[0.55300023, 0.95892817, 0.4098046 , ..., 0.77031938,
         0.69304293, 0.37460375],
        [0.12653099, 0.59493602, 0.77685985, ..., 0.62939041,
         0.92210709, 0.337875  ],
        [0.05125112, 0.46715559, 0.93754647, ..., 0.79565578,
         0.88836787, 0.36809613],
        ...,
        [0.7005413 , 0.08933286, 0.7774864 , ..., 0.05956999,
         0.0966079 , 0.52303651],
        [0.24476128, 0.72104897, 0.22824685, ..., 0.43575606,
         0.7677891 , 0.93990868],
        [0.40315297, 0.73813898, 0.04728745, ..., 0.80615597,
         0.98484109, 0.27726846]],

       [[0.50632646, 0.37938985, 0.88103216, ..., 0.14780678,
         0.31625244, 0.44758307],
        [0.29915104, 0.52279338, 0.95646194, ..., 0.17181485,
         0.72038657, 0.42614494],
        [0.37466106, 0.19714493, 0.72501396, ..., 0.20930514,
         0.27282198, 0.16639275],
        ...,
        [0.70150241, 0.81071275, 0.26675982, ..., 0.42253181,
         0.29483989, 0.06368046],
        [0.7

### Numpy Array Operations

In [101]:
# Reshaping array
reshaped_array = range_array.reshape((5, 1))
reshaped_array


array([[10],
       [12],
       [14],
       [16],
       [18]])

In [102]:
# Indexing and Slicing
sliced_array = arr_from_list[1:4]
sliced_array


array([20, 30, 15])

In [103]:
# Concatenation
concatenated_array = np.concatenate((arr_from_list, range_array))
concatenated_array

array([ 10,  20,  30,  15,  20,  55,  60,   0, -10,  70, -12,  10,  12,
        14,  16,  18])

In [104]:
# Addition Operation
sum_array = arr_from_list[:5] + range_array[:5]
sum_array

array([20, 32, 44, 31, 38])

In [105]:
# Multiplication Operation
product_array = arr_from_list * 2
product_array

array([ 20,  40,  60,  30,  40, 110, 120,   0, -20, 140, -24])

In [106]:
# Element-wise Multiplication
elementwise_multiplication = arr_from_list * np.tile(np.array([1, 2, 3, 4, 5]), len(arr_from_list)//5 + 1)[:len(arr_from_list)]
elementwise_multiplication


array([ 10,  40,  90,  60, 100,  55, 120,   0, -40, 350, -12])

### Reading a dataset and Converting it into a Numpy Array

In [107]:
dataset = pd.read_csv('vgsales.csv')
dataset = dataset.head(200)
dataset

Rank                                 Name Platform    Year         Genre  \
0       1                           Wii Sports      Wii  2006.0        Sports   
1       2                    Super Mario Bros.      NES  1985.0      Platform   
2       3                       Mario Kart Wii      Wii  2008.0        Racing   
3       4                    Wii Sports Resort      Wii  2009.0        Sports   
4       5             Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing   
..    ...                                  ...      ...     ...           ...   
195   196                       Guitar Hero II      PS2  2006.0          Misc   
196   197                      Resident Evil 5      PS3  2009.0        Action   
197   198                   Grand Theft Auto V     XOne  2014.0        Action   
198   199  Grand Theft Auto: Vice City Stories      PSP  2006.0        Action   
199   200                       FIFA Soccer 11      PS3  2010.0        Sports   

                Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
0                Nintendo     41.49     29.02      3.77         8.46   
1                Nintendo     29.08      3.58      6.81         0.77   
2                Nintendo     15.85     12.88      3.79         3.31   
3                Nintendo     15.75     11.01      3.28         2.96   
4                Nintendo     11.27      8.89     10.22         1.00   
..                    ...       ...       ...       ...          ...   
195             RedOctane      3.81      0.63      0.00         0.68   
196                Capcom      1.96      1.43      1.08         0.65   
197  Take-Two Interactive      2.66      2.01      0.00         0.41   
198  Take-Two Interactive      1.70      2.02      0.16         1.21   
199       Electronic Arts      0.60      3.29      0.06         1.13   

     Global_Sales  
0           82.74  
1           40.24  
2           35.82  
3           33.00  
4           31.37  
..            ...  
195          5.12  
196          5.11  
197          5.08  
198          5.08  
199          5.08  

[200 rows x 11 columns]

In [108]:
# sales from north america
na_sales = dataset['NA_Sales'].to_numpy()
na_sales

array([41.49, 29.08, 15.85, 15.75, 11.27, 23.2 , 11.38, 14.03, 14.59,
       26.93,  9.07,  9.81,  9.  ,  8.94,  9.09, 14.97,  7.01,  9.43,
       12.78,  4.75,  6.42, 10.83,  9.54,  9.63,  8.41,  6.06,  5.57,
        3.44,  6.85,  9.03,  5.89,  9.67,  5.17,  5.77,  4.99,  8.25,
        8.52,  5.54,  6.99,  6.75,  5.98,  2.55,  4.74,  7.97,  3.8 ,
        4.4 ,  6.91,  3.01,  6.16,  4.23,  6.16,  6.76,  4.02,  4.89,
        2.96,  4.99,  4.76,  5.99,  4.34,  5.08,  6.05,  6.72,  7.03,
        5.55,  3.66,  6.63,  3.01,  4.09,  5.84,  3.88,  5.91,  4.36,
        5.58,  2.01,  4.46,  5.03,  3.54,  1.11,  1.79,  6.82,  3.81,
        2.91,  1.06,  0.98,  5.8 ,  2.58,  2.91,  2.28,  2.82,  7.28,
        2.9 ,  3.66,  2.93,  2.8 ,  4.1 ,  3.78,  5.39,  3.24,  4.79,
        4.46,  3.83,  4.52,  3.51,  2.85,  3.27,  3.27,  3.68,  4.41,
        3.13,  2.47,  4.12,  4.14,  0.78,  2.71,  2.93,  2.77,  3.23,
        3.5 ,  4.15,  3.27,  3.1 ,  0.84,  1.67,  2.79,  0.79,  3.25,
        2.55,  3.74,

In [109]:
# Adding sales from all regions
total_game_sales = dataset['NA_Sales'] + dataset['EU_Sales'] + dataset['JP_Sales'] + dataset['Other_Sales']
total_game_sales.to_numpy()
total_game_sales

0      82.74
1      40.24
2      35.83
3      33.00
4      31.38
       ...  
195     5.12
196     5.12
197     5.08
198     5.09
199     5.08
Length: 200, dtype: float64

### Applying statistical functions

In [110]:
# Mean of total sales
mean_value = np.mean(total_game_sales, axis=0)
mean_value


10.291100000000002

In [111]:
# Median of total sales
median_value = np.median(total_game_sales, axis=0)
median_value

7.33

In [112]:
# Standard Deviation of total sales
std_dev = np.std(total_game_sales, axis=0)
std_dev


8.237470958370658

In [113]:
# Variance of total sales
variance = np.var(total_game_sales, axis=0)
variance

67.85592779000001

In [114]:
# Maximum value of total sales
max_value = np.max(total_game_sales, axis=0)
max_value

82.74000000000001

In [115]:
#Minimum value of total sales
min_value = np.min(total_game_sales, axis=0)
min_value

5.08

In [116]:
# Sum of total sales
sum_values = np.sum(total_game_sales, axis=0)
sum_values


2058.2200000000003

In [117]:
# Cumulative sum of total sales
cumsum_values = np.cumsum(total_game_sales, axis=0)
cumsum_values

0        82.74
1       122.98
2       158.81
3       191.81
4       223.19
        ...   
195    2037.85
196    2042.97
197    2048.05
198    2053.14
199    2058.22
Length: 200, dtype: float64